
-- CRIA BASE DE DADOS
CREATE DATABASE IF NOT EXISTS `freelatech` ;
USE `freelatech`;

-- CRIA TABELAS
CREATE TABLE IF NOT EXISTS `tb_categoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `tb_trabalho` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) NOT NULL,
  `DESCRICAO` varchar(255) NOT NULL,
  `ORCAMENTO` double(10,2) DEFAULT NULL,
  `TIPO` enum('FIXO','HORA') NOT NULL DEFAULT 'FIXO',
  `EXPERIENCIA` enum('INICIANTE','INTERMEDIARIO','EXPERIENTE') DEFAULT 'INICIANTE',
  `DATA_CRIACAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CATEGORIA_ID` int NOT NULL,
  `AUTOR_ID` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `CATEGORIA_ID` (`CATEGORIA_ID`),
  KEY `AUTOR_ID` (`AUTOR_ID`),
  CONSTRAINT `TRABALHO_CATEGORIAFK_1` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `tb_categoria` (`ID`),
  CONSTRAINT `TRABALHO_USUARIOFK_2` FOREIGN KEY (`AUTOR_ID`) REFERENCES `tb_usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb3;


CREATE TABLE IF NOT EXISTS `tb_usuarios` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `SENHA` varchar(255) DEFAULT NULL,
  `DATA_CRIACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `tb_proposta` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TRABALHO_ID` int NOT NULL,
  `USUARIO_ID` int NOT NULL,
  `PRECO` double(10,2) DEFAULT NULL,
  `PRAZO` varchar(255) DEFAULT NULL,
  `PROPOSTA` varchar(255) NOT NULL,
  `ACEITA` int NOT NULL DEFAULT '0',
  `FECHADO` int DEFAULT '0',
  `DATA_CRIACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `TRABALHO_ID` (`TRABALHO_ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  CONSTRAINT `PROPOSTA_TRABALHOFK_2` FOREIGN KEY (`TRABALHO_ID`) REFERENCES `tb_trabalho` (`ID`),
  CONSTRAINT `PROPOSTA_USUARIOFK_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `tb_usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `tb_perfil` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `BIOGRAFIA` varchar(255) DEFAULT NULL,
  `SOCIAL` varchar(255) DEFAULT NULL,
  `LOCALIZACAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  CONSTRAINT `PERFIL_USUARIOFK_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `tb_usuarios` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb3;


CREATE TABLE IF NOT EXISTS `tb_feedback` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PROPOSTA_ID` int NOT NULL,
  `CLIENTE_AVALIACAO` tinyint(1) DEFAULT NULL COMMENT 'Nota para o cliente postada pelo contratante',
  `CLIENTE_FEEDBACK` text COMMENT 'Feedback para o client postado pelo contratante',
  `CONTRATANTE_AVALIACAO` tinyint(1) DEFAULT NULL COMMENT 'Nota para o contratante postado pelo cliente',
  `CONTRATANTE_FEEDBACK` text COMMENT 'Feedback para o contratante postado pelo cliente',
  PRIMARY KEY (`ID`),
  KEY `PROPOSTA_ID` (`PROPOSTA_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `tb_mensagem` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `REMETENTE_ID` int NOT NULL,
  `DESTINATARIO_ID` int NOT NULL,
  `TRABALHO_ID` int DEFAULT NULL,
  `TEXTO` text NOT NULL,
  `DATA_ENVIO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb3;

-- INSERE DADOS INICIAIS

-- DADOS DE USUARIO
INSERT INTO `freelatech`.`tb_usuarios` (`ID`, `EMAIL`, `NOME`, `SENHA`) VALUES ('1', 'u1@u1.com', 'Usuario Contratante', '$2a$10$uWt2HuBlA8/6z8M3dMcxTOoF5hjHEnV3OuWjtuE4UgSvZPMlnaEHG');
INSERT INTO `freelatech`.`tb_usuarios` (`ID`, `EMAIL`, `NOME`, `SENHA`) VALUES ('2', 'u2@u2.com', 'Usuario Profissional', '$2a$10$uWt2HuBlA8/6z8M3dMcxTOoF5hjHEnV3OuWjtuE4UgSvZPMlnaEHG');

-- DADOS DE CATEGORIA

INSERT INTO `freelatech`.`tb_categoria` (`ID`, `NOME`) VALUES ('1', 'Software Development');
INSERT INTO `freelatech`.`tb_categoria` (`ID`, `NOME`) VALUES ('2', 'Design');
INSERT INTO `freelatech`.`tb_categoria` (`ID`, `NOME`) VALUES ('3', 'BackEnd Development');
INSERT INTO `freelatech`.`tb_categoria` (`ID`, `NOME`) VALUES ('4', 'FrontEnd Development');
INSERT INTO `freelatech`.`tb_categoria` (`ID`, `NOME`) VALUES ('5', 'Database Management');


