DROP TABLE IF EXISTS `TB_USUARIOS`;
CREATE TABLE IF NOT EXISTS `TB_USUARIOS` (
  `USUARIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `SENHA` varchar(255) DEFAULT NULL,
  `DATA_CRIACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USUARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `TB_PERFIL`;
CREATE TABLE IF NOT EXISTS `TB_PERFIL` (
  `PERFIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int(11) NOT NULL,
  `BIOGRAFIA` text,
  `SOCIAL` varchar(255) DEFAULT NULL,
  `LOCALIZACAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PERFIL_ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `TB_MENSAGEM`;
CREATE TABLE IF NOT EXISTS `TB_MENSAGEM` (
  `MENSAGEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REMETENTE_ID` int(11) NOT NULL,
  `DESTINATARIO_ID` int(11) NOT NULL,
  `TRABALHO_ID` int(11) DEFAULT NULL,
  `TEXTO` text NOT NULL,
  `DATA_ENVIO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MENSAGEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `TB_TRABALHO`;
CREATE TABLE IF NOT EXISTS `TB_TRABALHO` (
  `TRABALHO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `ORCAMENTO` double(10,2) DEFAULT NULL,
  `TIPO` enum('FIXO','HORA') NOT NULL DEFAULT 'FIXO',
  `EXPERIENCIA` enum('INICIANTE','INTERMEDIARIO','EXPERIENTE') DEFAULT 'INICIANTE',
  `DATA_CRIACAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CATEGORIA_ID` int(11) NOT NULL,
  `AUTOR_ID` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`TRABALHO_ID`),
  KEY `CATEGORIA_ID` (`CATEGORIA_ID`),
  KEY `AUTOR_ID` (`AUTOR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `TB_FEEDBACK`;
CREATE TABLE IF NOT EXISTS `TB_FEEDBACK` (
  `FEEDBACK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSTA_ID` int(11) NOT NULL,
  `CLIENTE_AVALIACAO` tinyint(1) DEFAULT NULL COMMENT 'Nota para o cliente postada pelo contratante',
  `CLIENTE_FEEDBACK` text COMMENT 'Feedback para o client postado pelo contratante',
  `CONTRATANTE_AVALIACAO` tinyint(1) DEFAULT NULL COMMENT 'Nota para o contratante postado pelo cliente',
  `CONTRATANTE_FEEDBACK` text COMMENT 'Feedback para o contratante postado pelo cliente',
  PRIMARY KEY (`FEEDBACK_ID`),
  KEY `PROPOSTA_ID` (`PROPOSTA_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `TB_CATEGORIA`;
CREATE TABLE IF NOT EXISTS `TB_CATEGORIA` (
  `CATEGORIA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  PRIMARY KEY (`CATEGORIA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `TB_PROPOSTA`;
CREATE TABLE IF NOT EXISTS `TB_PROPOSTA` (
  `PROPOSTA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRABALHO_ID` int(11) NOT NULL,
  `USUARIO_ID` int(11) NOT NULL,
  `PRECO` double(10,2) DEFAULT NULL,
  `PRAZO` varchar(255) DEFAULT NULL,
  `OFERTA` text NOT NULL,
  `ACEITA` tinyint(1) NOT NULL DEFAULT '0',
  `FECHADO` tinyint(1) DEFAULT '0',
  `DATA_CRIACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROPOSTA_ID`),
  KEY `TRABALHO_ID` (`TRABALHO_ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
















--
ALTER TABLE `TB_PROPOSTA`
  ADD CONSTRAINT `PROPOSTA_USUARIOFK_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `TB_USUARIOS` (`USUARIO_ID`),
  ADD CONSTRAINT `PROPOSTA_TRABALHOFK_2` FOREIGN KEY (`TRABALHO_ID`) REFERENCES `TB_TRABALHO` (`TRABALHO_ID`);

--

--
ALTER TABLE `TB_TRABALHO`
  ADD CONSTRAINT `TRABALHO_CATEGORIAFK_1` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `TB_CATEGORIA` (`CATEGORIA_ID`),
  ADD CONSTRAINT `TRABALHO_USUARIOFK_2` FOREIGN KEY (`AUTOR_ID`) REFERENCES `TB_USUARIOS` (`USUARIO_ID`);


--
ALTER TABLE `TB_PERFIL`
  ADD CONSTRAINT `PERFIL_USUARIOFK_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `TB_USUARIOS` (`USUARIO_ID`);
COMMIT;
